# 特定のバージョンを指定し、このファイル内で使用できる文法が固定
version: '3'

# 起動したいコンテナを定義。本記事では3つのコンテナ（nginx、app、mysql）を定義
services:
  # Nginxの定義
  nginx:
    # Nginxコンテナに使用するイメージを指定
    image: nginx:1.25.0
    # ホストマシンのポートをコンテナのポートにマッピング
    ports:
      # <ホストマシンのポート>:<コンテナのポート>
      - 8000:80
  # app:
  # mysql:
